### ISSUE TITLE
Error when activating plugin

### ISSUE THREAD

**Issue by MichielA01** [delower186/wp-todo#1]
I downloaded the wp-todo plugin version 1.1.2 and dropped it in the plugins folder, but when activating it throws an error:

------------------------------------------------
Warning: dirname() expects exactly 1 parameter, 2 given in /public/sites/..../wp-content/plugins/wp-todo/inc/Base/BaseController.php on line 15

Warning: dirname() expects exactly 1 parameter, 2 given in /public/sites/..../wp-content/plugins/wp-todo/inc/Base/BaseController.php on line 16

Warning: dirname() expects exactly 1 parameter, 2 given in /public/sites/..../wp-content/plugins/wp-todo/inc/Base/BaseController.php on line 17

Warning: dirname() expects exactly 1 parameter, 2 given in /public/sites/..../wp-content/plugins/wp-todo/inc/Base/BaseController.php on line 15

Warning: dirname() expects exactly 1 parameter, 2 given in /public/sites/..../wp-content/plugins/wp-todo/inc/Base/BaseController.php on line 16

Warning: dirname() expects exactly 1 parameter, 2 given in /public/sites/..../wp-content/plugins/wp-todo/inc/Base/BaseController.php on line 17

..
The plugin generated 1116 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

---------------------------------------
(I removed my site name from the errors..)

My wordpress version is 4.9.5.

Any ideas what the issue can be?

**Comment by MichielA01** [comment]
The problem is that {{dirname( __FILE__ , 2 )}} works only with PHP7
Nested dirname are needed for earlier versions.
Below my changed basecontroller.php, which does not throw an error at activation. 

{code}
<?php
/**
* @package wptodo
*/
namespace Inc\Base;


class BaseController
{
	public static $plugin_path;
	public static $plugin_url;
	public static $plugin;
	
	public function __construct(){
		self::$plugin_path = plugin_dir_path( dirname(dirname( __FILE__ )) );
		self::$plugin_url = plugin_dir_url( dirname(dirname( __FILE__ )) );
		self::$plugin = plugin_basename( dirname(dirname(dirname( __FILE__ ))) ) . '/wp-todo.php';
	}
}
{code}

**Comment by MichielA01** [comment]
... above does not solve all issues.. adding a task also throws an error now:

`Catchable fatal error: Argument 1 passed to Inc\Base\Model::wptodo_edit_task() must be an instance of Inc\Base\int, string given, called in /public/sites/www.poda.nl/wp-content/plugins/wp-todo/inc/Base/Model.php on line 317 and defined in /public/sites/www.poda.nl/wp-content/plugins/wp-todo/inc/Base/Model.php on line 288`

So probably PHP7 is required?

**Comment by delower186** [comment]
@MichielA01 Yes, you are correct PHP7 is required.
