### ISSUE TITLE
No instructions

### ISSUE THREAD

**Issue by MethylBromide** [delower186/wp-todo#11]
It would be very helpful to have more of a guide especially as regards the shortcode. Does it take any arguments? In particular, is there any way to specify which tasks are displayed? We want users to see only their own tasks on the "to do" page of the website.

The plugin website in the WordPress.org catalog is a broken link, so if there was ever any documentation, it's missing now.

**Comment by delower186** [comment]
All issues fixed, you will find detail walk through video in plugin page at wordpress repository and released new version here https://wordpress.org/plugins/wp-todo/
