### ISSUE TITLE
view and shortcut

### ISSUE THREAD

**Issue by jkwebco** [delower186/wp-todo#3]
not showing timer, allways shows Danger! This Task is OverDue 

works fine in edit admin

view and edit on frontend not working 
view in admin not working 

version version 5.3.2, wordpress

**Comment by jkwebco** [comment]
Trying to start timer when countdown already at 0

Your issue is with the date just being a string, not an object See this [one](https://jsfiddle.net/m8v9z4LL/) for a working example.

The API docs does mention [FlipClock](http://flipclockjs.com/api#time).Time

**Comment by jkwebco** [comment]
admin.php line 113	$timesecond = strtotime($deadline);

**Comment by delower186** [comment]
That's fixed, thanks
