### ISSUE TITLE
User Roles

### ISSUE THREAD

**Issue by HTMLPhD** [delower186/wp-todo#5]
I have a  site which employs bbpress.  As such I am both bbp_keymaster and administrator.  The way the code is written the $role of administrator is overwritten by bbp_administrator.

See  /home/wp-content/plugins/wp-todo/inc/Pages lines 119-140:
	public static function get_role(){

		$current_user = wp_get_current_user();

		foreach($current_user->roles as $role){

			$role;
		}

		return $role;

	}

I hacked the code to make it work for me:

	public static function get_role(){

		$current_user = wp_get_current_user();

		foreach($current_user->roles as $role){

			$role;
			break;
		}

		return $role;

	}

There may be other plugins which will have a similar complication, so I would suggest that the line should likely be:

		foreach($current_user->roles as $role){

			if ($role = "administrator" || $role = "editor') { return $role; }
                }

                return $role;
      }

**Comment by HTMLPhD** [comment]
Oops (bad quote):

if ($role = "administrator" || $role = "editor') { return $role; }

**Comment by delower186** [comment]
@HTMLPhD Your suggestion applied, thanks
