### ISSUE TITLE
Getting blank pages

### ISSUE THREAD

**Issue by wchornung** [delower186/wp-todo#7]
Love the To-Do plugin.  Unfortunately, a new unnamed page also gets added each time we add a task.  Is there any way to prevent this?

**Comment by delower186** [comment]
@wchornung This is must be a conflict with other plugin or theme. Please at first update the plugin then revert to a default theme if it is not theme then deactivate all plugins except WP To Do and activate one by one to find out the conflicted plugin and inspect browser and check the console to find if there is any js error, if there is, take screenshot and send me, then I will be able to help.

**Comment by Liezel-Chetty** [comment]
Hi, 

I have updated the plugin and have deactivated all plugins but still it is hitting a blank page...

please have a look https://www.damasygroup.com/?page=wp-todo&view=2

**Comment by Oburoni** [comment]
I have to a issue Look this. 
![image](https://user-images.githubusercontent.com/68870134/92758011-9b9ec280-f38e-11ea-8399-1e1a4b8a7097.png) and i cant add a taks and this plugin is the best for my website.

**Comment by delower186** [comment]
Please update to the latest version
